---
- name: Cleanup and remove deployed application
  hosts: appservers
  become: true
  vars:
    app_dir: /root/canva

  tasks:
    - name: Stop and remove all Docker containers using docker-compose
      command: docker-compose down
      args:
        chdir: "{{ app_dir }}"
      ignore_errors: yes

    - name: Stop and remove all Docker containers using docker compose (v2)
      command: docker compose down
      args:
        chdir: "{{ app_dir }}"
      ignore_errors: yes

    - name: Stop all running containers
      shell: docker stop $(docker ps -aq) 2>/dev/null || true
      ignore_errors: yes

    - name: Remove all containers
      shell: docker rm -f $(docker ps -aq) 2>/dev/null || true
      ignore_errors: yes

    - name: Remove all images
      shell: docker rmi -f $(docker images -aq) 2>/dev/null || true
      ignore_errors: yes

    - name: Remove all volumes
      shell: docker volume rm $(docker volume ls -q) 2>/dev/null || true
      ignore_errors: yes

    - name: Remove all networks
      shell: docker network prune -f 2>/dev/null || true
      ignore_errors: yes

    - name: Full Docker system prune
      command: docker system prune -af --volumes
      ignore_errors: yes

    - name: Stop Docker service
      systemd:
        name: docker
        state: stopped
      ignore_errors: yes

    - name: Remove Docker packages
      apt:
        name:
          - docker.io
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
          - docker-compose
        state: absent
        autoremove: yes
        purge: yes
      ignore_errors: yes

    - name: Remove Docker directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/docker
        - /var/lib/containerd
        - /etc/docker
        - /usr/local/bin/docker-compose
      ignore_errors: yes

    - name: Remove application directory
      file:
        path: "{{ app_dir }}"
        state: absent

    - name: Remove git
      apt:
        name: git
        state: absent
        autoremove: yes
      ignore_errors: yes

- name: Cleanup Nginx load balancer configuration
  hosts: loadbalancer
  become: true

  tasks:
    - name: Stop Nginx service
      systemd:
        name: nginx
        state: stopped
      ignore_errors: yes

    - name: Remove Nginx site configuration
      file:
        path: /etc/nginx/sites-enabled/canva.conf
        state: absent

    - name: Remove Nginx site configuration from available
      file:
        path: /etc/nginx/sites-available/canva.conf
        state: absent

    - name: Remove Nginx completely
      apt:
        name: nginx
        state: absent
        autoremove: yes
        purge: yes

    - name: Remove Nginx directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/nginx
        - /var/log/nginx
        - /var/www/html
      ignore_errors: yes

- name: Display cleanup summary
  hosts: all
  tasks:
    - name: Cleanup complete
      debug:
        msg: "Complete cleanup finished for {{ inventory_hostname }} - everything nuked!"
